I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Chapters/lagoon2.rpy", line 36, in script
    mr_grucki_cat "My little playthings, it's time for a game. Will you offer yourselves to my barbed tongue?"
Exception: Sayer 'mr_grucki_cat' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Chapters/lagoon2.rpy", line 36, in script
    mr_grucki_cat "My little playthings, it's time for a game. Will you offer yourselves to my barbed tongue?"
  File "C:\Users\ismea\OneDrive\Desktop\Projects\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\ismea\OneDrive\Desktop\Projects\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mr_grucki_cat' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Gris 1.0
Tue Dec 26 00:37:24 2023
