I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Chapters/lagoon2.rpy", line 143, in script
    with shake
  File "game/Chapters/lagoon2.rpy", line 143, in <module>
    with shake
NameError: name 'shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Chapters/lagoon2.rpy", line 143, in script
    with shake
  File "C:\Users\ismea\OneDrive\Desktop\Projects\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\ismea\OneDrive\Desktop\Projects\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\ismea\OneDrive\Desktop\Projects\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/Chapters/lagoon2.rpy", line 143, in <module>
    with shake
NameError: name 'shake' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Gris 1.0
Fri Dec 29 17:18:57 2023
